Support german language
CubiclDev/coffee-break-slack-bot pull request #3
Opened 2022-08-25 05:43 UTC by SelenaHa

What this PR does
- support german language in Slack message

2022-08-26 07:23 UTC, BeWe11 requested changes

2022-08-26 07:23 UTC, BeWe11 commented on slack_bot/app.py
> +from typing import List
```suggestion
```
Die Verwendung von `list` als Type wurde eigentlich mit Python 3.9 eingeführt, welches wir für den Kaffeebot verwenden. Hast du eventuell nicht die richtige venv aktiviert beim Entwickeln?

2022-08-26 07:23 UTC, BeWe11 commented on slack_bot/app.py
> +def get_message(user_name_1: str, user_name_2: str) -> str:
Ich definiere Methoden gerne vor ihrem ersten Aufruf. Das ist aber eine Stilfrage, ich glaube wir haben da schonmal drüber disktutiert und du machst es genau andersrum :D kann so bleiben, wollte es nur anmerken.

2022-08-26 07:23 UTC, BeWe11 commented on tests/test_slack_bot.py
>             'Your coffee bot ☕'
Diese Tests würden sich auch super durch eine Parametrisierung mit dem `@pytest.mark.parametrize` Decorator abbilden lassen. Sprachcode und erwartete Nachricht als Parameter, dann brauchst du nur eine einzige Testfunktion für alle drei Tests. Da die Zahl der Tests hier gering ist und sich daran wahrscheinlich auch nicht viel ändern wird ist das nicht unbedingt notwendig, ich will nur Anmerken, dass das hier ein guter Use-case dafür ist.

2022-08-26 07:23 UTC, BeWe11 commented on README.md
> +
```suggestion
If you would like to override default values of variables, copy the `terraform.tfvars.dist` file to `terraform.tfvars` and fill in values for the predefined variable names.

List of all variables:
- `language`: ISO 639-1 language code for the language of the message. Supported are 'en' and 'de'. The default language is english. Unsupported languages fall back to english as well.

```

2022-08-26 07:23 UTC, BeWe11 commented on slack_bot/app.py
> +           'Your coffee bot ☕'
Ich find's grundsätzlich nicht so schön, die Nachrichten hier in die Funktion zu legen. Man könnte alle Language Templates in eine JSON Datei legen, die dann von der `get_message` Methode gelesen wird. Allerdings wäre das auch irgendwie overkill, weil ich nicht davon ausgehe, das in nächster Zeit mehr Sprachen hinzugefügt werden 😄

2022-08-26 09:30 UTC, BeWe11 approved these changes

2022-08-30 14:17 UTC, MariusRumpf approved these changes

2022-09-01 04:55 UTC, merged