Evaluate slack user info
CubiclDev/coffee-break-slack-bot pull request #4
Opened 2022-09-09 06:54 UTC by SelenaHa

What this PR does

- evaluate slack deleted flag
- evaluate slack status

2022-09-09 16:37 UTC, BeWe11 requested changes

2022-09-09 16:37 UTC, BeWe11 commented on README.md
> +- 🤒
```suggestion
Users that are absent are automatically excluded. Absence is determined by checking if one of the following status emojis is set:
- 🌴
- 🤒
```
Das mit dem "gelöscht" Status würde ich hier garnicht erwähnen, das ist so oder so sinnvoll. Den Rest hab ich nur etwas komprimiert.

2022-09-09 16:37 UTC, BeWe11 commented on slack_bot/app.py
> +    language = os.environ.get('LANGUAGE', 'en')
Wieso hast du die Anführungszeichen geändert (hier und überall sonst)? Wir benutzen `"` eigentlich als Standard.

2022-09-09 16:37 UTC, BeWe11 commented on slack_bot/app.py
> +def get_filtered_users(users: list[str], client: WebClient) -> list[str]:
```suggestion
def filter_users(users: list[str], client: WebClient) -> list[str]:
```
Das ist mal wieder Geschmackssache, aber ich benutze den `get_` Prefix gerne, wenn tatsächlich Daten irgendwo her beschafft werden, aber nicht für Transformationen oder Filterungen. In diesem Fall finde ich es sprechender, die Operation zu beschreiben (in diesem Fall dann "filter_users").

2022-09-09 16:37 UTC, BeWe11 commented on slack_bot/app.py
> +    absence_emojis = [':palm_tree:', ':face_with_thermometer:']
Wollen wir daraus eine globale `ABSENCE_EMOJIS` Variable machen?

2022-09-09 16:37 UTC, BeWe11 commented on tests/test_slack_bot.py
> +    is_included_user
Magst du das so formatieren wie Black&isort das machen? Am einfachsten ist es sogar, du lässt beides einfach drüber laufen (ohne dafür jetzt eine Pipeline aufzusetzen).

2022-09-09 16:37 UTC, BeWe11 commented on slack_bot/app.py
> +    if user_info['deleted'] is True:
```suggestion
    if user_info['deleted']:
```
Der Vergleich mit True ist implizit schon da.

2022-09-09 16:37 UTC, BeWe11 commented on slack_bot/app.py
> +    if status_expiration != 0 and status_expiration < tomorrow.timestamp():
Ist `status_expiration == 0` gleichbedeutent mit "keine Expiration"?

Ist die Logik hier effektiv so, dass jemand auch erst am Dienstag 11:00 wieder aus dem Urlaub kommen könnte und trotzdem eine Kaffeepause bekommt?

2022-09-09 16:37 UTC, BeWe11 commented on tests/test_slack_bot.py
> +    [(
Die Formatierung hier ist auf jeden Fall auch nicht Black konform :D ist nicht so wild, aber kannst ja eventuell black trotzdem nochmal drüber laufen lassen.

2022-09-13 05:31 UTC, SelenaHa commented on slack_bot/app.py
> +    language = os.environ.get('LANGUAGE', 'en')
Wollte es einheitlich, vorher war beides da. Können uns auf " auch für dieses Projekt einigen.

2022-09-13 05:37 UTC, SelenaHa commented on slack_bot/app.py
> +    if status_expiration != 0 and status_expiration < tomorrow.timestamp():
0 steht drin, wenn keine Expiration gesetzt ist.
11 Uhr wird wahrscheinlich drin sein, da der Timestamp auch Sekunden enthält. Sicherheitshalber kann aus < aber auch <= werden.

Die Frage an der Stelle ist sowieso, wo das Limit sein sollte.

2022-09-16 09:51 UTC, BeWe11 approved these changes

2022-09-16 09:51 UTC, BeWe11 commented on slack_bot/app.py
> +    if status_expiration != 0 and status_expiration < tomorrow.timestamp():
Ja das ist genau die Frage, was mich hier bisschen gestörte hat ist, dass der Zeitraum davon abhängt, wann das Script ausgeführt wird. Ist aber erstmal nicht schlimm, wir lassen es so 👍

2022-09-23 11:55 UTC, caroga1073 approved these changes

2022-09-30 05:53 UTC, merged